const mongoose = require("mongoose");

const ministerCredentialSchema = new mongoose.Schema(
  {
    streetAddress: { type: String },
    name: { type: String, required: true },
    email: { type: String, required: true },
    apartment: { type: String },
    city: { type: String },
    state: { type: String },
    zip: { type: String },
    country: { type: String },
    phone: { type: String },
    How_did_you_learn_about: { type: String },
    agreement: { type: Boolean },
    apartment1: { type: String },
    city1: { type: String },
    state1: { type: String },
    zip1: { type: String },
    country1: { type: String },
    howlong1: { type: String },
    streetAddress1: { type: String },
    apartment2: { type: String },
    city2: { type: String },
    state2: { type: String },
    zip2: { type: String },
    country2: { type: String },
    howlong2: { type: String },
    streetAddress2: { type: String },
    Sex: { type: String },
    maritalState: { type: String },
    areYouUsCitizen: { type: String },
    visaOrSocialSecurity: { type: String },
    sponsorName: { type: String },
    presentMinistryRole: { type: String },
    isFullTime: { type: String },
    ministryDescription: { type: String },
    callTestimony: { type: String },
    isSupported: { type: String },
    ministerialRoles: { type: String },
    currentIncome: { type: String },
    yearsInMinistry: { type: String },
    salvationTestimony: { type: String },
    isChristInLife: { type: String },
    baptizedWater: { type: String },
    baptizedSpirit: { type: String },
    unityInBody: { type: String },
    soulWinner: { type: String },
    lifestyleStandard: { type: String },
    doYouBelieve: { type: String },
    pastorName: { type: String },
    fellowshipStatus: { type: String },
    pastorContact: { type: String },
    address: { type: String },
    dob: { type: String },
    substanceUse: { type: String },
    theologicalViews: { type: String },
    misconductAccusation: { type: String },
    legalConviction: { type: String },
    explanation: { type: String },
    alreadyCredentialed: { type: String },
    paragraph: { type: String },
    holySpiritBaptism: { type: String },
    waterBaptism: { type: String },
    justLivingByFaith: { type: String },
    ordinationConsent: { type: String },
    actsDisqualify: { type: String },
    willSurrender: { type: String },
    declaration: { type: Boolean },
    electronicSignature: { type: String },
    fullName: { type: String },
    submissionDate: { type: String },
    credentialCategory: { type: String },
    materialsConsent: { type: Boolean },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("MinisterCredential", ministerCredentialSchema);
